name: Documentation check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  checkdocs:
    name: Verify generated
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Generate docs
        run: |
          go generate

      - name: Verify nothing to generate
        run: |
          if [[ "$(git diff --name-only -- generatedocs/generated/documentation.go)" != "" ]]; then
            echo "documentation not generated"
            exit 1
          fi